version: "3.9"
services:
  dd-agent:
    image: datadog/agent:latest
    ports:
      - 8126:8126/tcp
  nodejs-webapp:
    image: boylikhit/node-app
    links:
      - dd-agent
    ports:
      - 3001:3000
